import type { Doctor, Patient, UserProfile, TimelineItem } from '../types';

export const INITIAL_DOCTORS: Doctor[] = [
  { id: 'doc-shirao', displayName: '白尾医師', active: true, displayOrder: 1 },
  { id: 'doc-fukaya', displayName: '深谷医師', active: true, displayOrder: 2 },
  { id: 'doc-okada', displayName: '岡田医師', active: true, displayOrder: 3 },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    uid: 'user-admin-01',
    displayName: '管理者 スタッフ',
    email: 'admin@example.com',
    role: 'admin',
    active: true,
  },
  {
    uid: 'user-staff-01',
    displayName: '鈴木 スタッフ',
    email: 'staff@example.com',
    role: 'staff',
    active: true,
  },
  {
    uid: 'user-doc-shirao',
    displayName: '白尾 医師',
    email: 'shirao@example.com',
    role: 'doctor',
    doctorId: 'doc-shirao',
    active: true,
  },
  {
    uid: 'user-doc-fukaya',
    displayName: '深谷 医師',
    email: 'fukaya@example.com',
    role: 'doctor',
    doctorId: 'doc-fukaya',
    active: true,
  },
  {
    uid: 'user-doc-okada',
    displayName: '岡田 医師',
    email: 'okada@example.com',
    role: 'doctor',
    doctorId: 'doc-okada',
    active: true,
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'patient-p-001',
    patientCode: 'P-001',
    displayName: '患者A',
    consultationDate: '2026-07-15',
    chiefComplaint: '右膝の運動時痛',
    consultationDetails: '半月板損傷の既往あり。ジョギング中に右膝内側に鈍痛を生じる。湿布等の保存的療法を継続中。',
    doctorAssessment: '右膝関節内側裂隙に軽度の圧痛を認める。腫脹・水腫はなし。',
    doctorAdvice: '過度な荷重運動は控え、水泳やエアロバイク等の低負荷運動を中心とすること。',
    followUpPlan: '週1回の経過観察とリハビリテーション指示。',
    assignedDoctorId: 'doc-shirao',
    assignedDoctorName: '白尾医師',
    status: 'waiting_doctor',
    notes: '架空のサンプル患者データです。',
    archived: false,
    unreadCount: 1,
    createdBy: 'user-admin-01',
    createdAt: new Date('2026-07-15T10:00:00Z').toISOString(),
    updatedAt: new Date('2026-07-20T14:30:00Z').toISOString(),
  },
  {
    id: 'patient-p-002',
    patientCode: 'P-002',
    displayName: '患者B',
    consultationDate: '2026-07-10',
    chiefComplaint: '腰部痛',
    consultationDetails: '長時間のデスクワーク後に腰部全域に違和感と張り感あり。下肢への放散痛はなし。',
    doctorAssessment: '筋・筋膜性腰痛症の疑い。神経学的所見は正常。',
    doctorAdvice: '姿勢の改善および腰背部のストレッチを指導。',
    followUpPlan: '症状増悪がなければ経過観察終了。',
    assignedDoctorId: 'doc-fukaya',
    assignedDoctorName: '深谷医師',
    status: 'completed',
    notes: '架空のサンプル患者データです。',
    archived: false,
    unreadCount: 0,
    createdBy: 'user-admin-01',
    createdAt: new Date('2026-07-10T11:00:00Z').toISOString(),
    updatedAt: new Date('2026-07-18T09:15:00Z').toISOString(),
  },
  {
    id: 'patient-p-003',
    patientCode: 'P-003',
    displayName: '患者C',
    consultationDate: '2026-07-18',
    chiefComplaint: '左肩関節可動域制限',
    consultationDetails: '結髪・結帯動作時に肩関節外側に痛みが走り、90度以上の挙上が困難。',
    doctorAssessment: '肩関節周囲炎（五十肩）の初期像。',
    doctorAdvice: '痛みの強くない範囲での振り子運動および温熱療法を試みる。',
    followUpPlan: '経過を見ながら可動域訓練の強度を調整。',
    assignedDoctorId: 'doc-okada',
    assignedDoctorName: '岡田医師',
    status: 'in_progress',
    notes: '架空のサンプル患者データです。',
    archived: false,
    unreadCount: 0,
    createdBy: 'user-staff-01',
    createdAt: new Date('2026-07-18T13:20:00Z').toISOString(),
    updatedAt: new Date('2026-07-22T16:45:00Z').toISOString(),
  },
  {
    id: 'patient-p-004',
    patientCode: 'P-004',
    displayName: '患者D',
    consultationDate: '2026-07-21',
    chiefComplaint: '足関節捻挫後の不快感',
    consultationDetails: '1ヶ月前の足関節内反捻挫。歩行時の外果下の不安定感。',
    doctorAssessment: '前距腓靱帯の軽度弛緩性あり。',
    doctorAdvice: '足関節周囲筋力強化とテーピング指導。',
    followUpPlan: 'スポーツ復帰に向けた段階的負荷増大。',
    assignedDoctorId: 'doc-shirao',
    assignedDoctorName: '白尾医師',
    status: 'waiting_staff',
    notes: '架空のサンプル患者データです。',
    archived: false,
    unreadCount: 1,
    createdBy: 'user-staff-01',
    createdAt: new Date('2026-07-21T09:00:00Z').toISOString(),
    updatedAt: new Date('2026-07-25T11:00:00Z').toISOString(),
  },
  {
    id: 'patient-p-005',
    patientCode: 'P-005',
    displayName: '患者E',
    consultationDate: '2026-07-22',
    chiefComplaint: '頸部・肩こりからの頭痛',
    consultationDetails: '夕方になると後頭部にかけて緊張型頭痛が発生。',
    doctorAssessment: '僧帽筋・頭板状筋のこわばり。',
    doctorAdvice: '適度な休息と首まわりのストレッチ。',
    followUpPlan: '経過観察。',
    assignedDoctorId: 'unassigned',
    assignedDoctorName: '担当医未設定',
    status: 'observing',
    notes: '担当医未設定のサンプルです。',
    archived: false,
    unreadCount: 0,
    createdBy: 'user-admin-01',
    createdAt: new Date('2026-07-22T15:00:00Z').toISOString(),
    updatedAt: new Date('2026-07-22T15:00:00Z').toISOString(),
  },
];

export const INITIAL_TIMELINES: Record<string, TimelineItem[]> = {
  'patient-p-001': [
    {
      id: 'time-p001-1',
      patientId: 'patient-p-001',
      type: 'progress_report',
      body: '安静時痛はありません。階段下降時に痛みが残っています。運動量をどの程度まで増やしてよいか確認をお願いします。',
      authorId: 'user-staff-01',
      authorName: '鈴木 スタッフ',
      authorRole: 'staff',
      requiresResponse: true,
      priority: 'soon',
      confirmedBy: [
        {
          userId: 'user-admin-01',
          userName: '管理者 スタッフ',
          confirmedAt: new Date('2026-07-20T14:35:00Z').toISOString(),
        },
      ],
      createdAt: new Date('2026-07-20T14:30:00Z').toISOString(),
      updatedAt: new Date('2026-07-20T14:30:00Z').toISOString(),
    },
  ],
  'patient-p-002': [
    {
      id: 'time-p002-1',
      patientId: 'patient-p-002',
      type: 'doctor_question',
      body: '患者様より軽度のウォーキングを再開したい旨の申し出がありました。可否と留意点のご指示をお願いいたします。',
      authorId: 'user-staff-01',
      authorName: '鈴木 スタッフ',
      authorRole: 'staff',
      requiresResponse: true,
      priority: 'normal',
      confirmedBy: [],
      createdAt: new Date('2026-07-17T10:00:00Z').toISOString(),
      updatedAt: new Date('2026-07-17T10:00:00Z').toISOString(),
    },
    {
      id: 'time-p002-2',
      patientId: 'patient-p-002',
      type: 'doctor_response',
      body: '日常生活で症状が増悪しなければ、軽い運動から段階的に再開してください。15分程度の平地歩行から開始し、痛みの増強がなければ時間を延ばしてください。',
      authorId: 'user-doc-fukaya',
      authorName: '深谷 医師',
      authorRole: 'doctor',
      requiresResponse: false,
      priority: 'normal',
      confirmedBy: [
        {
          userId: 'user-staff-01',
          userName: '鈴木 スタッフ',
          confirmedAt: new Date('2026-07-18T09:15:00Z').toISOString(),
        },
      ],
      createdAt: new Date('2026-07-18T09:00:00Z').toISOString(),
      updatedAt: new Date('2026-07-18T09:00:00Z').toISOString(),
    },
  ],
  'patient-p-004': [
    {
      id: 'time-p004-1',
      patientId: 'patient-p-004',
      type: 'doctor_response',
      body: 'テーピングの巻き方についての指導用リーフレットをお渡しし、今週末から軽いアジリティトレーニングを開始してください。',
      authorId: 'user-doc-shirao',
      authorName: '白尾 医師',
      authorRole: 'doctor',
      requiresResponse: false,
      priority: 'normal',
      confirmedBy: [],
      createdAt: new Date('2026-07-25T11:00:00Z').toISOString(),
      updatedAt: new Date('2026-07-25T11:00:00Z').toISOString(),
    },
  ],
};
